<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MohitPrakash-PC" ignored="0" name="Default test" tests="1" failures="1" timestamp="17 Mar 2017 02:08:35 GMT" time="7.983" errors="0">
  <testcase name="tcase1" time="1.366" classname="testcases.TC_001">
    <failure type="java.io.IOException" message="Source &amp;apos;C:\Users\MOHITP~1\AppData\Local\Temp\screenshot4653006384644300317.png&amp;apos; exists but is not a directory">
      <![CDATA[java.io.IOException: Source 'C:\Users\MOHITP~1\AppData\Local\Temp\screenshot4653006384644300317.png' exists but is not a directory
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1370)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1237)
	at snaps.Takesnaps.takescreeshot(Takesnaps.java:15)
	at testcases.TC_001.tcase1(TC_001.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- tcase1 -->
</testsuite> <!-- Default test -->
