<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7983" started-at="2017-03-17T02:08:27Z" finished-at="2017-03-17T02:08:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7983" started-at="2017-03-17T02:08:27Z" finished-at="2017-03-17T02:08:35Z">
      <class name="testcases.TC_001">
        <test-method status="PASS" signature="createdr()[pri:0, instance:testcases.TC_001@573f2bb1]" name="createdr" is-config="true" duration-ms="5695" started-at="2017-03-17T07:38:27Z" finished-at="2017-03-17T07:38:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createdr -->
        <test-method status="FAIL" signature="tcase1()[pri:0, instance:testcases.TC_001@573f2bb1]" name="tcase1" duration-ms="1366" started-at="2017-03-17T07:38:33Z" finished-at="2017-03-17T07:38:34Z">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Source 'C:\Users\MOHITP~1\AppData\Local\Temp\screenshot4653006384644300317.png' exists but is not a directory]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Source 'C:\Users\MOHITP~1\AppData\Local\Temp\screenshot4653006384644300317.png' exists but is not a directory
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1370)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1237)
	at snaps.Takesnaps.takescreeshot(Takesnaps.java:15)
	at testcases.TC_001.tcase1(TC_001.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tcase1 -->
        <test-method status="PASS" signature="amet()[pri:0, instance:testcases.TC_001@573f2bb1]" name="amet" is-config="true" duration-ms="906" started-at="2017-03-17T07:38:34Z" finished-at="2017-03-17T07:38:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amet -->
      </class> <!-- testcases.TC_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
